package view; 

import control.GerenciarViagemControl;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.entidades.Carro;
        
public class InternalGerenciarViagem extends javax.swing.JInternalFrame {
    
    
    GerenciarViagemControl gerenciarViagemControl;
   
    public InternalGerenciarViagem() {
        initComponents();
    }
    
    public InternalGerenciarViagem(GerenciarViagemControl control) {
        initComponents();
        gerenciarViagemControl = control;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfKmInicial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfKmFinal = new javax.swing.JTextField();
        btSalvarViagem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbViagens = new javax.swing.JTable();
        btEditarViagem = new javax.swing.JButton();
        btRemoverViagem = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Minhas viagens");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gerenciamento de viagens");

        jLabel2.setText("Km inicial");

        jLabel3.setText("Destino");

        jLabel4.setText("Km final");

        btSalvarViagem.setText("Salvar");
        btSalvarViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarViagemActionPerformed(evt);
            }
        });

        jLabel5.setText("Carro");

        tbViagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbViagens);

        btEditarViagem.setText("Editar");
        btEditarViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarViagemActionPerformed(evt);
            }
        });

        btRemoverViagem.setText("Remover");
        btRemoverViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverViagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(tfKmInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(tfKmFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(tfDestino)
                        .addComponent(btSalvarViagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btEditarViagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemoverViagem))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btRemoverViagem)
                            .addComponent(btEditarViagem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4)
                                .addComponent(tfKmInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfKmFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvarViagem)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditarViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarViagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditarViagemActionPerformed

    private void btSalvarViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarViagemActionPerformed
        // TODO add your handling code here:
        gerenciarViagemControl.cadastrarViagemAction();
        
        
    }//GEN-LAST:event_btSalvarViagemActionPerformed

    private void btRemoverViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverViagemActionPerformed
        // TODO add your handling code here:
        gerenciarViagemControl.removerViagemAction();
    }//GEN-LAST:event_btRemoverViagemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditarViagem;
    private javax.swing.JButton btRemoverViagem;
    private javax.swing.JButton btSalvarViagem;
    public static final javax.swing.JComboBox<Carro> cbCarros = new javax.swing.JComboBox<>();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbViagens;
    private javax.swing.JTextField tfDestino;
    private javax.swing.JTextField tfKmFinal;
    private javax.swing.JTextField tfKmInicial;
    // End of variables declaration//GEN-END:variables

    public JComboBox<Carro> getCbCarros() {
        return cbCarros;
    }

    public JTextField getTfDestino() {
        return tfDestino;
    }

    public void setTfDestino(JTextField tfDestino) {
        this.tfDestino = tfDestino;
    }

    public JTextField getTfKmFinal() {
        return tfKmFinal;
    }

    public void setTfKmFinal(JTextField tfKmFinal) {
        this.tfKmFinal = tfKmFinal;
    }

    public JTextField getTfKmInicial() {
        return tfKmInicial;
    }

    public void setTfKmInicial(JTextField tfKmInicial) {
        this.tfKmInicial = tfKmInicial;
    }

    public JTable getTbViagens() {
        return tbViagens;
    }

    public void setTbViagens(JTable tbViagens) {
        this.tbViagens = tbViagens;
    }
    
    

    

}
